### ISSUE TITLE
generated file path warning

### ISSUE THREAD

**Issue by ZezhongWang** [thejinchao/protoc-gen-turbolink#1]
Generated file name "Private\\SGreeter\\GreeterService_Private.h" does not conform to the Protobuf generation specification. Note that the file name must be relative, use "/" instead of "\", and not use "." or ".." as part of the file name. Buf will continue without error here, but please raise an issue with the maintainer of the plugin and reference https://github.com/protocolbuffers/protobuf/blob/95e6c5b4746dd7474d540ce4fb375e3f79a086f8/src/google/protobuf/compiler/plugin.proto#L122

直接使用 protoc 而不是使用你的 generate_code.cmd 时会产生上面的 warning

**Comment by thejinchao** [comment]
不是很明白，其实 generate_code.cmd 也是调用的protoc, 产生这个警告具体执行的什么命令产生的？看起来应该是文件路径的问题，能具体贴一下命令内容吗？谢谢

**Comment by ZezhongWang** [comment]
fixed in #5
