### ISSUE TITLE
package syntax in .proto file should be lower case.

### ISSUE THREAD

**Issue by ZezhongWang** [thejinchao/protoc-gen-turbolink#2]
Example:

```
syntax = "proto3";

package Greeter; // should be "greeter"
option go_package = "./Greeter";

message HelloRequest {
	string name = 1;
}
```

If change "Greeter" to lowercase there will be some other inconsistencies.

**Comment by ZezhongWang** [comment]
Any reason that the folder starts with 'S' letter? like "SGreeter"

**Comment by thejinchao** [comment]
`S` means `Service`. This letter is added to avoid the same name as other directories in the project. For example, in a large project, there may be a source file that is `Greeter/GreeterService.h`, so I add an `S in front of these automatically generated directories, to prevent possible conflicts during include. 
The package names in my project all start with capital letters. I have never tried to change it to lowercase. Thank you for reminding me. I'll fix it.

**Comment by ZezhongWang** [comment]
My new PR solves this problem. You can write package names with lower case letters, but it will generate capital folder names.
