### ISSUE TITLE
Python log warning when cooking: Rename one of them using 'ScriptName' meta-data.

### ISSUE THREAD

**Issue by 6r0m** [thejinchao/protoc-gen-turbolink#8]
UATHelper: Packaging (Windows): LogPython: Warning: 'EGrpcGoogleProtobufValueKind' and 'GrpcGoogleProtobufValueKind' have the same name (GrpcGoogleProtobufValueKind) when exposed to Python. Rename one of them using 'ScriptName' meta-data.

possible adding `UENUM(BlueprintType, meta=(ScriptName="EGrpcGoogleProtobufValueKind"))` solves the problem

**Comment by thejinchao** [comment]
already fixed in the latest version.
